// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_VMXQLEOoYsYnxUFJ0FEIjsx3Yp_iBZM',
    appId: '1:579295691644:web:25866367c5c1ea7a7fdaf9',
    messagingSenderId: '579295691644',
    projectId: 'woolify-4182c',
    authDomain: 'woolify-4182c.firebaseapp.com',
    storageBucket: 'woolify-4182c.appspot.com',
    measurementId: 'G-X96XPBZVXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANdFSMmE5vy0a0F-gt-NJ1GBquaIh6wzg',
    appId: '1:579295691644:android:7f00a2bb0c5524137fdaf9',
    messagingSenderId: '579295691644',
    projectId: 'woolify-4182c',
    storageBucket: 'woolify-4182c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Bg8_BkEw5PT2TDamznns6GYPGnn_jNg',
    appId: '1:579295691644:ios:385a43ea5604c1b57fdaf9',
    messagingSenderId: '579295691644',
    projectId: 'woolify-4182c',
    storageBucket: 'woolify-4182c.appspot.com',
    iosBundleId: 'com.example.woolify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Bg8_BkEw5PT2TDamznns6GYPGnn_jNg',
    appId: '1:579295691644:ios:979ce52a286fd8c67fdaf9',
    messagingSenderId: '579295691644',
    projectId: 'woolify-4182c',
    storageBucket: 'woolify-4182c.appspot.com',
    iosBundleId: 'com.example.woolify.RunnerTests',
  );
}
